/-
Character values of finite groups lie in cyclotomic fields.

This file formalizes the classical result that the values of any
finite-dimensional complex character of a finite group `G` lie in the
cyclotomic field `ℚ(ζₙ)`, where `n = exponent G`. Since `ℚ(ζₙ)` is a
number field of characteristic zero, it embeds (non-canonically) into
`ℂ`, and we phrase the result in terms of one such ring homomorphism
`φ : CyclotomicField n ℚ → ℂ`.
-/

import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots
import Mathlib.LinearAlgebra.Eigenspace.Charpoly
import Mathlib.RepresentationTheory.Basic
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.Data.Complex.Basic

open Polynomial

namespace FLT.CharacterValuesCyclotomic

/-- **Exponent of a finite group is positive.** For any finite group `G`,
the exponent `Monoid.exponent G` is a positive natural number. -/
lemma exponent_pos (G : Type*) [Group G] [Finite G] :
    0 < Monoid.exponent G := by
  sorry

/-- **Cyclotomic field embeds in `ℂ`.** For any positive natural number `n`,
there exists a ring homomorphism `CyclotomicField n ℚ → ℂ`. -/
lemma cyclotomic_embeds_in_complex (n : ℕ) [NeZero n] :
    ∃ φ : CyclotomicField n ℚ →+* ℂ, True := by
  sorry

/-- **Image of `ζ` is a primitive `n`-th root of unity.** Let `n` be a
positive natural number and let `ζ₀ = IsCyclotomicExtension.zeta n ℚ
(CyclotomicField n ℚ)` be the distinguished primitive `n`-th root of
unity in `CyclotomicField n ℚ`. For any injective ring homomorphism
`φ : CyclotomicField n ℚ → ℂ`, the element `φ ζ₀` is a primitive
`n`-th root of unity in `ℂ`. -/
lemma image_zeta_is_primitive_root (n : ℕ) [NeZero n]
    (φ : CyclotomicField n ℚ →+* ℂ) (hφ : Function.Injective φ) :
    IsPrimitiveRoot
      (φ (IsCyclotomicExtension.zeta n ℚ (CyclotomicField n ℚ))) n := by
  sorry

/-- **`f^n = 1` implies the charpoly splits with roots in `μₙ`.** Let `V`
be a finite-dimensional complex vector space, let `n ≥ 1`, and let
`f : V →ₗ[ℂ] V` with `f ^ n = 1`. Then `f.charpoly` splits over `ℂ`,
and every root `μ` of `f.charpoly` satisfies `μ ^ n = 1`. -/
lemma charpoly_roots_are_roots_of_unity
    {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
    {n : ℕ} (hn : 1 ≤ n) (f : V →ₗ[ℂ] V) (hf : f ^ n = 1) :
    (LinearMap.charpoly f).Splits ∧
      ∀ μ ∈ (LinearMap.charpoly f).roots, μ ^ n = 1 := by
  sorry

/-- **Trace of a finite-order endomorphism is a sum of `n`-th roots of
unity.** Let `V` be a finite-dimensional complex vector space, let
`n ≥ 1`, and let `f : V →ₗ[ℂ] V` with `f ^ n = 1`. Then
`LinearMap.trace ℂ V f` equals the sum of `f.charpoly.roots`, and every
root in this multiset is an `n`-th root of unity. -/
lemma trace_eq_sum_roots_of_unity
    {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
    {n : ℕ} (hn : 1 ≤ n) (f : V →ₗ[ℂ] V) (hf : f ^ n = 1) :
    LinearMap.trace ℂ V f = (LinearMap.charpoly f).roots.sum ∧
      ∀ μ ∈ (LinearMap.charpoly f).roots, μ ^ n = 1 := by
  sorry

/-- **`n`-th roots of unity lie in the subring generated by a primitive
root.** If `ζ ∈ ℂ` is a primitive `n`-th root of unity and `μ ∈ ℂ`
satisfies `μ ^ n = 1`, then there exists `k : ℕ` with `μ = ζ ^ k`. -/
lemma nth_root_in_powers {n : ℕ} [NeZero n] {ζ : ℂ}
    (hζ : IsPrimitiveRoot ζ n) {μ : ℂ} (hμ : μ ^ n = 1) :
    ∃ k : ℕ, μ = ζ ^ k := by
  sorry

/-- **Trace lies in the range of `φ`.** Let `n ≥ 1`, let
`φ : CyclotomicField n ℚ → ℂ` be a ring homomorphism, and view
`ζ := φ (IsCyclotomicExtension.zeta n ℚ (CyclotomicField n ℚ))` as a
primitive `n`-th root of unity in `ℂ`. For any finite-dimensional
complex vector space `V` and any `f : V →ₗ[ℂ] V` with `f ^ n = 1`,
`LinearMap.trace ℂ V f` lies in `φ.range`. -/
lemma trace_in_cyclotomic_range
    {n : ℕ} [NeZero n] (φ : CyclotomicField n ℚ →+* ℂ)
    {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
    (f : V →ₗ[ℂ] V) (hf : f ^ n = 1) :
    LinearMap.trace ℂ V f ∈ φ.range := by
  sorry

/-- **Finite group element raised to the exponent is the identity in any
representation.** Let `G` be a finite group, let `V` be a complex
vector space, and let `ρ : Representation ℂ G V`. With
`n := Monoid.exponent G`, for every `g : G`, `(ρ g) ^ n = 1` in
`V →ₗ[ℂ] V`. -/
lemma rho_g_pow_exp {G : Type*} [Group G] [Finite G]
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (ρ : Representation ℂ G V) (g : G) :
    (ρ g) ^ (Monoid.exponent G) = 1 := by
  sorry

/-- **Character values lie in the cyclotomic field.** Let `G` be a
finite group and let `n = Monoid.exponent G`. There exists a ring
homomorphism `φ : CyclotomicField n ℚ → ℂ` such that for every
finite-dimensional complex representation `ρ : Representation ℂ G V`
and every `g : G`, the trace `LinearMap.trace ℂ V (ρ g)` lies in
`φ.range`. -/
theorem brauer_character_in_cyclotomic
    (G : Type*) [Group G] [Finite G] :
    ∃ φ : CyclotomicField (Monoid.exponent G) ℚ →+* ℂ,
      ∀ {V : Type*} [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]
        (ρ : Representation ℂ G V) (g : G),
          LinearMap.trace ℂ V (ρ g) ∈ φ.range := by
  sorry

end FLT.CharacterValuesCyclotomic
