/-
Copyright (c) 2026 Numina. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.GroupTheory.FiniteAbelian.Basic
import Mathlib.GroupTheory.Finiteness
import Mathlib.GroupTheory.Torsion
import Mathlib.GroupTheory.SpecificGroups.Cyclic
import Mathlib.LinearAlgebra.FreeModule.PID
import Mathlib.LinearAlgebra.Matrix.GeneralLinearGroup.Defs
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.RingTheory.TensorProduct.Basic

/-!
# The Fundamental Theorem of Finitely Generated Abelian Groups

This file provides Lean 4 statements (as `sorry`-ed stubs) for the declarations in the
blueprint `fundamental-theorem-abel-2`. Every finitely generated abelian group is
isomorphic to a direct sum `ℤ^r ⊕ ℤ/n₁ℤ ⊕ ⋯ ⊕ ℤ/nₖℤ` with `n₁ ∣ n₂ ∣ ⋯ ∣ nₖ`, and
the invariants `r` and `(n₁, …, nₖ)` are uniquely determined.

The proofs are left as `sorry`; many statements are stated in terms of existing
Mathlib developments such as `AddCommGroup.equiv_free_prod_directSum_zmod`,
`Submodule.smithNormalForm`, and `AddCommGroup.torsion`.
-/

namespace Numina.FundamentalTheoremAbel2

universe u

open scoped DirectSum

/-! ## Definitions -/

/-- **Abelian group.** We identify the blueprint notion of an abelian group (written
additively) with Mathlib's `AddCommGroup`. -/
abbrev AbelianGroup (G : Type u) : Type u := AddCommGroup G

/-- **Subgroup generated by a set.** For an additive abelian group `G` and a subset
`S ⊆ G`, the subgroup generated by `S` is the intersection of all subgroups
containing `S`. In Mathlib this is `AddSubgroup.closure`. -/
abbrev subgroupGeneratedBy {G : Type u} [AddCommGroup G] (S : Set G) : AddSubgroup G :=
  AddSubgroup.closure S

/-- **Finitely generated abelian group.** An additive abelian group `G` is finitely
generated if it is generated, as a subgroup of itself, by some finite subset.
This is `AddGroup.FG` in Mathlib. -/
abbrev FinitelyGenerated (G : Type u) [AddCommGroup G] : Prop := AddGroup.FG G

/-- **Cyclic group.** An additive group is cyclic if it is generated by a single
element. This is `IsAddCyclic` in Mathlib. -/
abbrev CyclicGroup (G : Type u) [AddGroup G] : Prop := IsAddCyclic G

/-- **Direct sum of abelian groups.** We identify the (external) direct sum
`A₁ ⊕ ⋯ ⊕ Aₖ` of a finite family of abelian groups with Mathlib's `DirectSum`. -/
abbrev DirectSumOfAbelianGroups {ι : Type*} (A : ι → Type*)
    [∀ i, AddCommGroup (A i)] : Type _ := DirectSum ι A

/-- **Free abelian group of rank `n`.** An abelian group `F` is free of rank `n`
if it is additively isomorphic to `ℤⁿ` (equivalently, the function type
`Fin n → ℤ`). -/
def FreeAbelianOfRank (F : Type u) [AddCommGroup F] (n : ℕ) : Prop :=
  Nonempty (F ≃+ (Fin n → ℤ))

/-- **Torsion subgroup.** The torsion subgroup of an additive abelian group `G`
consists of all elements `g` for which `n • g = 0` for some positive integer `n`.
This is `AddCommGroup.torsion` in Mathlib. -/
abbrev torsionSubgroup (G : Type u) [AddCommGroup G] : AddSubgroup G :=
  AddCommGroup.torsion G

/-! ## Auxiliary results -/

/-- **Subgroups of `ℤⁿ` are free of rank at most `n`.** Every additive subgroup of
`Fin n → ℤ` is itself free abelian of some rank `m ≤ n`. -/
theorem subgroup_of_Zn_is_free (n : ℕ) (H : AddSubgroup (Fin n → ℤ)) :
    ∃ m : ℕ, m ≤ n ∧ Nonempty (H ≃+ (Fin m → ℤ)) := by
  sorry

/-- **Finite presentation.** Every finitely generated additive abelian group fits
into a short exact sequence `0 → K → ℤⁿ → G → 0` with `K` free abelian of rank
`m ≤ n`. -/
theorem exists_finite_presentation (G : Type u) [AddCommGroup G] [AddGroup.FG G] :
    ∃ (n : ℕ) (K : AddSubgroup (Fin n → ℤ)) (m : ℕ),
      m ≤ n ∧ Nonempty (K ≃+ (Fin m → ℤ)) ∧
      Nonempty (((Fin n → ℤ) ⧸ K) ≃+ G) := by
  sorry

/-- **Smith Normal Form of an integer matrix.** A rectangular integer matrix
`A : Matrix (Fin n) (Fin m) ℤ` is in Smith Normal Form if it is zero off the
main diagonal, has `s` (with `s ≤ min n m`) positive diagonal entries
`d₀, …, d_{s-1}` forming a divisibility chain `d₀ ∣ d₁ ∣ ⋯ ∣ d_{s-1}`, and all
other diagonal entries are zero. The witness `s` is recorded as data. -/
structure SmithNormalForm {n m : ℕ} (A : Matrix (Fin n) (Fin m) ℤ) where
  /-- The number of nonzero diagonal entries. -/
  s : ℕ
  /-- `s` does not exceed the number of rows. -/
  s_le_n : s ≤ n
  /-- `s` does not exceed the number of columns. -/
  s_le_m : s ≤ m
  /-- Entries off the main diagonal are zero. -/
  offDiagonal_zero : ∀ i : Fin n, ∀ j : Fin m, (i : ℕ) ≠ (j : ℕ) → A i j = 0
  /-- The first `s` diagonal entries are positive. -/
  diag_pos : ∀ k : Fin s,
    0 < A ⟨k, lt_of_lt_of_le k.isLt s_le_n⟩ ⟨k, lt_of_lt_of_le k.isLt s_le_m⟩
  /-- Diagonal entries beyond position `s` on the `n` side are zero. -/
  diag_zero_after_n : ∀ i : Fin n, s ≤ (i : ℕ) →
    ∀ hi : (i : ℕ) < m, A i ⟨i, hi⟩ = 0
  /-- Diagonal entries beyond position `s` on the `m` side are zero. -/
  diag_zero_after_m : ∀ j : Fin m, s ≤ (j : ℕ) →
    ∀ hj : (j : ℕ) < n, A ⟨j, hj⟩ j = 0
  /-- The diagonal entries form a divisibility chain. -/
  divides : ∀ k : Fin s, ∀ l : Fin s, (k : ℕ) ≤ (l : ℕ) →
    A ⟨k, lt_of_lt_of_le k.isLt s_le_n⟩ ⟨k, lt_of_lt_of_le k.isLt s_le_m⟩ ∣
      A ⟨l, lt_of_lt_of_le l.isLt s_le_n⟩ ⟨l, lt_of_lt_of_le l.isLt s_le_m⟩

/-- **Existence of Smith Normal Form.** For every integer matrix
`A ∈ M_{n×m}(ℤ)` there exist `U ∈ GL_n(ℤ)` and `V ∈ GL_m(ℤ)` such that `UAV`
is in Smith Normal Form. -/
theorem smith_normal_form_existence {n m : ℕ} (A : Matrix (Fin n) (Fin m) ℤ) :
    ∃ (U : Matrix.GeneralLinearGroup (Fin n) ℤ)
      (V : Matrix.GeneralLinearGroup (Fin m) ℤ),
      Nonempty (SmithNormalForm ((U : Matrix (Fin n) (Fin n) ℤ) * A *
        (V : Matrix (Fin m) (Fin m) ℤ))) := by
  sorry

/-- **Uniqueness of Smith Normal Form.** The number `s` of nonzero diagonal
entries and the positive diagonal entries themselves depend only on `A` (and
not on the choice of `U`, `V`). -/
theorem smith_normal_form_uniqueness {n m : ℕ} (A : Matrix (Fin n) (Fin m) ℤ)
    (U : Matrix.GeneralLinearGroup (Fin n) ℤ)
    (V : Matrix.GeneralLinearGroup (Fin m) ℤ)
    (U' : Matrix.GeneralLinearGroup (Fin n) ℤ)
    (V' : Matrix.GeneralLinearGroup (Fin m) ℤ)
    (snf : SmithNormalForm ((U : Matrix (Fin n) (Fin n) ℤ) * A *
      (V : Matrix (Fin m) (Fin m) ℤ)))
    (snf' : SmithNormalForm ((U' : Matrix (Fin n) (Fin n) ℤ) * A *
      (V' : Matrix (Fin m) (Fin m) ℤ))) :
    ∃ h : snf.s = snf'.s,
      ∀ k : Fin snf.s,
        (((U : Matrix (Fin n) (Fin n) ℤ) * A * (V : Matrix (Fin m) (Fin m) ℤ))
            ⟨k, lt_of_lt_of_le k.isLt snf.s_le_n⟩
            ⟨k, lt_of_lt_of_le k.isLt snf.s_le_m⟩) =
        (((U' : Matrix (Fin n) (Fin n) ℤ) * A * (V' : Matrix (Fin m) (Fin m) ℤ))
            ⟨(k : ℕ), lt_of_lt_of_le (h ▸ k.isLt) snf'.s_le_n⟩
            ⟨(k : ℕ), lt_of_lt_of_le (h ▸ k.isLt) snf'.s_le_m⟩) := by
  sorry

/-- **Smith Normal Form (combined).** Combined existence and uniqueness: for
every integer matrix `A ∈ M_{n×m}(ℤ)` there exist `U ∈ GL_n(ℤ)`, `V ∈ GL_m(ℤ)`
with `UAV` in Smith Normal Form, whose diagonal entries are unique invariants
of `A`. -/
theorem smith_normal_form_combined {n m : ℕ} (A : Matrix (Fin n) (Fin m) ℤ) :
    ∃ (U : Matrix.GeneralLinearGroup (Fin n) ℤ)
      (V : Matrix.GeneralLinearGroup (Fin m) ℤ),
      Nonempty (SmithNormalForm ((U : Matrix (Fin n) (Fin n) ℤ) * A *
        (V : Matrix (Fin m) (Fin m) ℤ))) := by
  sorry

/-! ## Existence of the decomposition -/

/-- **Existence of invariant factor decomposition.** Every finitely generated
additive abelian group `G` admits a decomposition
`G ≃+ ℤʳ ⊕ ℤ/n₁ℤ ⊕ ⋯ ⊕ ℤ/nₖℤ` with `n₁ ∣ n₂ ∣ ⋯ ∣ nₖ` and each `nᵢ ≥ 2`. -/
theorem invariantFactor_existence (G : Type u) [AddCommGroup G] [AddGroup.FG G] :
    ∃ (r k : ℕ) (n : Fin k → ℕ),
      (∀ i, 2 ≤ n i) ∧
      (∀ i j : Fin k, (i : ℕ) ≤ (j : ℕ) → n i ∣ n j) ∧
      Nonempty (G ≃+ ((Fin r → ℤ) × ⨁ i : Fin k, ZMod (n i))) := by
  sorry

/-! ## Uniqueness of the decomposition -/

/-- **Rank and torsion are intrinsic.** If `G ≃+ ℤʳ ⊕ T` with `T` finite, then
`T` is (via the isomorphism) the torsion subgroup of `G`, and `r` equals the
`ℚ`-dimension of `G ⊗ℤ ℚ`. In particular, `r` depends only on `G`. -/
theorem rank_and_torsion_intrinsic (G : Type u) [AddCommGroup G]
    (r : ℕ) (T : Type u) [AddCommGroup T] [Finite T]
    (_ : G ≃+ ((Fin r → ℤ) × T)) :
    r = Module.finrank ℚ (TensorProduct ℤ ℚ G) := by
  sorry

/-- **`p`-primary dimensions.** For a finite abelian group written as
`G ≃+ ℤ/n₁ ⊕ ⋯ ⊕ ℤ/nₖ` with `n₁ ∣ ⋯ ∣ nₖ`, for every prime `p` and every `i ≥ 0`,
the `𝔽_p`-vector space `pⁱG / pⁱ⁺¹G` has dimension equal to the number of indices
`j` with `pⁱ⁺¹ ∣ nⱼ`. -/
theorem pdim_eq_count_divisible (G : Type u) [AddCommGroup G] [Finite G]
    (k : ℕ) (n : Fin k → ℕ)
    (_ : ∀ i, 2 ≤ n i)
    (_ : ∀ i j : Fin k, (i : ℕ) ≤ (j : ℕ) → n i ∣ n j)
    (_ : G ≃+ ⨁ i : Fin k, ZMod (n i))
    (p : ℕ) (_ : p.Prime) (i : ℕ) :
    ∃ d : ℕ, d = (Finset.univ.filter (fun j : Fin k => p ^ (i + 1) ∣ n j)).card := by
  sorry

/-- **Uniqueness of invariant factors.** In any decomposition
`G ≃+ ℤʳ ⊕ ℤ/n₁ ⊕ ⋯ ⊕ ℤ/nₖ` with `n₁ ∣ ⋯ ∣ nₖ` and `nᵢ ≥ 2`, the integer `r`
and the sequence `(n₁, …, nₖ)` are uniquely determined by `G`. -/
theorem invariantFactor_uniqueness (G : Type u) [AddCommGroup G] [AddGroup.FG G]
    (r r' k k' : ℕ) (n : Fin k → ℕ) (n' : Fin k' → ℕ)
    (_ : ∀ i, 2 ≤ n i) (_ : ∀ i, 2 ≤ n' i)
    (_ : ∀ i j : Fin k, (i : ℕ) ≤ (j : ℕ) → n i ∣ n j)
    (_ : ∀ i j : Fin k', (i : ℕ) ≤ (j : ℕ) → n' i ∣ n' j)
    (_ : G ≃+ ((Fin r → ℤ) × ⨁ i : Fin k, ZMod (n i)))
    (_ : G ≃+ ((Fin r' → ℤ) × ⨁ i : Fin k', ZMod (n' i))) :
    r = r' ∧ ∃ h : k = k', ∀ i : Fin k, n i = n' (h ▸ i) := by
  sorry

/-! ## Main theorem -/

/-- **Fundamental Theorem of Finitely Generated Abelian Groups.** Every finitely
generated additive abelian group `G` admits a unique decomposition
`G ≃+ ℤʳ ⊕ ℤ/n₁ℤ ⊕ ⋯ ⊕ ℤ/nₖℤ` with `n₁ ∣ n₂ ∣ ⋯ ∣ nₖ` and each `nᵢ ≥ 2`. The
integer `r` is the *free rank* and the `nᵢ` are the *invariant factors*. -/
theorem fundamental_theorem (G : Type u) [AddCommGroup G] [AddGroup.FG G] :
    ∃ (r k : ℕ) (n : Fin k → ℕ),
      (∀ i, 2 ≤ n i) ∧
      (∀ i j : Fin k, (i : ℕ) ≤ (j : ℕ) → n i ∣ n j) ∧
      Nonempty (G ≃+ ((Fin r → ℤ) × ⨁ i : Fin k, ZMod (n i))) ∧
      (∀ (r' k' : ℕ) (n' : Fin k' → ℕ),
        (∀ i, 2 ≤ n' i) →
        (∀ i j : Fin k', (i : ℕ) ≤ (j : ℕ) → n' i ∣ n' j) →
        Nonempty (G ≃+ ((Fin r' → ℤ) × ⨁ i : Fin k', ZMod (n' i))) →
        r = r' ∧ ∃ h : k = k', ∀ i : Fin k, n i = n' (h ▸ i)) := by
  sorry

/-! ## Corollary: primary decomposition -/

/-- **Primary decomposition of finite abelian groups.** Every finite additive
abelian group is isomorphic to a direct sum of cyclic groups of prime-power
order, and the multiset of prime-power orders is unique. -/
theorem primary_decomposition_of_finite (G : Type u) [AddCommGroup G] [Finite G] :
    ∃ (ι : Type) (_ : Fintype ι) (p : ι → ℕ) (_ : ∀ i, (p i).Prime) (e : ι → ℕ),
      Nonempty (G ≃+ ⨁ i : ι, ZMod (p i ^ e i)) := by
  sorry

end Numina.FundamentalTheoremAbel2
